import {
  ControlPointInfo,
  BeatmapDifficultySection,
  Vector2,
  SliderPath,
  HitSample,
  IHitObject,
  IHasPathWithRepeats,
  IHasGenerateTicks,
  IHasSliderVelocity,
} from 'osu-classes';

import { StandardEventGenerator } from './StandardEventGenerator';
import { StandardHitObject } from './StandardHitObject';
import { SliderHead } from './SliderHead';
import { SliderTail } from './SliderTail';
import { StandardHitWindows } from '../Scoring';

export class Slider extends StandardHitObject
  implements IHitObject, IHasPathWithRepeats, IHasSliderVelocity, IHasGenerateTicks {

  /**
   * This is obsolete and will be removed soon.
   * @deprecated
   */
  legacyLastTickOffset?: number;

  hitWindows = StandardHitWindows.empty;

  startPosition: Vector2 = new Vector2(0, 0);

  get startX(): number {
    this._updateHeadPosition();

    return this.startPosition.x;
  }

  set startX(value: number) {
    this.startPosition.x = value;
    this._updateHeadPosition();
  }

  get startY(): number {
    this._updateHeadPosition();

    return this.startPosition.y;
  }

  set startY(value: number) {
    this.startPosition.y = value;
    this._updateHeadPosition();
  }

  get endX(): number {
    this._updateTailPosition();

    return this.endPosition.x;
  }

  set endX(value: number) {
    this.endPosition.x = value;
    this._updateTailPosition();
  }

  get endY(): number {
    this._updateTailPosition();

    return this.endPosition.y;
  }

  set endY(value: number) {
    this.endPosition.y = value;
    this._updateTailPosition();
  }

  get endTime(): number {
    return this.startTime + this.spans * this.distance / this.velocity;
  }

  get duration(): number {
    return this.endTime - this.startTime;
  }

  get endPosition(): Vector2 {
    return this.startPosition.add(this.path.curvePositionAt(1, this.spans));
  }

  path: SliderPath = new SliderPath();

  get distance(): number {
    return this.path.distance;
  }

  set distance(value: number) {
    this.path.distance = value;
  }

  /**
   * The position of the cursor at the point of completion of this slider if it was hit
   * with as few movements as possible. This is set and used by difficulty calculation.
   */
  lazyEndPosition?: Vector2;

  /**
   * The distance travelled by the cursor upon completion of this slider if it was hit
   * with as few movements as possible. This is set and used by difficulty calculation.
   */
  lazyTravelDistance = 0;

  /**
   * The time taken by the cursor upon completion of this slider if it was hit
   * with as few movements as possible. This is set and used by difficulty calculation.
   */
  lazyTravelTime = 0;

  nodeSamples: HitSample[][] = [];

  private _repeats = 0;

  get repeats(): number {
    return this._repeats;
  }

  set repeats(value: number) {
    this._repeats = value;
    this._updateHeadPosition();
    this._updateTailPosition();
  }

  get spans(): number {
    return this.repeats + 1;
  }

  get spanDuration(): number {
    return this.duration / this.spans;
  }

  /**
   * The computed velocity of this {@link Slider}.
   * This is the amount of path distance travelled in 1 ms.
   */
  velocity = 1;

  /**
   * Spacing between {@link SliderTick}s of this {@link Slider}.
   */
  tickDistance = 0;

  /**
   * Use {@link tickDistanceMultiplier} instead.
   * @deprecated
   */
  tickRate = 1;

  /**
   * An extra multiplier that affects the number of {@link SliderTick}s 
   * generated by this {@link Slider}.
   * An increase in this value increases {@link tickDistance}, 
   * which reduces the number of ticks generated.
   */
  tickDistanceMultiplier = 1;

  sliderVelocity = 1;
  generateTicks = true;

  get head(): SliderHead | null {
    const obj = this.nestedHitObjects.find((n) => n instanceof SliderHead);

    return obj as SliderHead || null;
  }

  get tail(): SliderTail | null {
    const obj = this.nestedHitObjects.find((n) => n instanceof SliderTail);

    return obj as SliderTail || null;
  }

  applyDefaultsToSelf(controlPoints: ControlPointInfo, difficulty: BeatmapDifficultySection): void {
    super.applyDefaultsToSelf(controlPoints, difficulty);

    const timingPoint = controlPoints.timingPointAt(this.startTime);

    const scoringDistance = StandardHitObject.BASE_SCORING_DISTANCE
      * difficulty.sliderMultiplier * this.sliderVelocity;

    this.velocity = scoringDistance / timingPoint.beatLength;
    this.tickDistance = this.generateTicks
      ? scoringDistance / difficulty.sliderTickRate * this.tickDistanceMultiplier
      : Infinity;
  }

  createNestedHitObjects(): void {
    this.nestedHitObjects = [];

    for (const nested of StandardEventGenerator.generateSliderTicks(this)) {
      this.nestedHitObjects.push(nested);
    }
  }

  private _updateHeadPosition(): void {
    if (this.head !== null) {
      this.head.startPosition = this.startPosition;
    }
  }

  private _updateTailPosition(): void {
    if (this.tail !== null) {
      this.tail.startPosition = this.endPosition;
    }
  }

  /**
   * Creates a deep copy of this slider.
   * @returns Cloned slider.
   */
  clone(): this {
    const cloned = super.clone();

    cloned.nodeSamples = this.nodeSamples.map((n) => n.map((s) => s.clone()));
    cloned.velocity = this.velocity;
    cloned.repeats = this.repeats;
    cloned.path = this.path.clone();
    cloned.tickDistance = this.tickDistance;
    cloned.tickRate = this.tickRate;
    cloned.legacyLastTickOffset = this.legacyLastTickOffset;

    return cloned;
  }
}
